# pytorch_lightning==2.1.0
data:
  class_path: dataloader.dataset.NYUDataModule
  init_args:
    nyuv2_data_root: '/home/ashkanganj/workspace/dataset/nyu_depth_v2/official_splits'
    # nyuv2_data_root: '/home/ashka/data/nyu_depth_v2_labeled.mat'
    img_size: [480, 640]  # Adjust if your NYUDataModule expects a tuple for img_size
    remove_white_border: True
    batch_size: 1
    num_workers: 0  # Adjust based on your requirements
    use_labels: True
    num_cluster: 5

model:
  invert_depth: True

ckpt_path: /home/ashkanganj/workspace/PrecisionDepthFocus/checkpoints/NYUBestScaleInv10Full.ckpt