# pytorch_lightning==2.1.0
data:
  # For DDFF12DataModule
  class_path: dataloader.dataset.DDFF12DataModule
  init_args:
    ddff12_data_root: '/home/ashkanganj/workspace/dataset/dff_trainVal.h5'
    img_size: [383, 552]  # Adjust if your DDFF12DataModule expects a tuple for img_size
    remove_white_border: True
    batch_size: 1
    num_workers: 5
    use_labels: True
    num_cluster: 5
model:
  invert_depth: False

ckpt_path: /home/ashkanganj/workspace/2023-HybridDepth-DepthProject/checkpoints/DDFF12BestScaleInv.ckpt